### ISSUE TITLE
getMovieInfoById() fails for some movies.

### ISSUE THREAD

**Issue by oscard0m** [gism/filmaffinity2IMDB#12]
When I execute the main.py, I can enter my user and password but it fails during the extraction. The message shown is the following one:

```
All movies pushed to queue to get all movie information.
ERROR FOUND: change regular expression at getMovieInfoById() for movie county. Probably FA changed web page structure. Movie ID: 394186
ERROR FOUND: change regular expression at getMovieInfoById() for movie county. Probably FA changed web page structure. Movie ID: 412013
ERROR FOUND: change regular expression at getMovieInfoById() for movie county. Probably FA changed web page structure. Movie ID: 132582
ERROR FOUND: change regular expression at getMovieInfoById() for movie county. Probably FA changed web page structure. Movie ID: 304107
```

**Comment by rolgalan** [comment]
Hi,

I've forked this repo and I've already fixed this issue, and some other stuff. The problem now is to log-in at IMDB. You may take a look at this branch:
https://github.com/rolgalan/filmaffinity2IMDB/tree/disable-fa-login

If I manage to solve it, I'll contact with the maintainer to ask for a PR.

**Comment by txemi** [comment]
I have seen in your branch that more that disabling login you removed that code. Could it be more useful to disable it at runtime when not neccesary for actual operation instead removing it in case this project evolve to do things that need write permission on FA?

**Comment by rolgalan** [comment]
Sure txemi, great idea! 

I mostly wanted to test if I was able to gather the movies without login, and after that I started to fix things... Actually I will separate the no-login feature and the bugfixing to separate branches.

**Comment by gism** [comment]
Hola @rolgalan,

Nice to see you contribution. It is a pity but I have the project a bit unattended.
I like the idea of using user ID instead of user/password for "read only" actions.

The first error you get is due to bad regular expression. I've seen in your fork a new regular expression. Does it fix the problem? is there any other problem?

I'm going to check your code and update mine.

Many thanks both of you.

**Comment by rolgalan** [comment]
Hola @gism !

I've fixed the regexp for countries and some mispelling errors. Everything is currently on my master. I can do a PR with all of this if you want.

I've just scanned the 1200 movies on my profile and now there is a problem with the cast regexp:
_ERROR FOUND: change regular expression at getMovieInfoById() for movie cast. Probably FA changed web page structure. Movie ID: 719680_
I've checked the movies with problems and this prompts when there is no _Cast_ section, so it's not a real issue :)

The biggest problem right now is to log-in at IMDB, which has been changed as well.

So happy that you like the userID idea :)

**Comment by gism** [comment]
> The biggest problem right now is to log-in at IMDB, which has been changed as well.

Yesterday I was looking at IMDB log-in form.
It has changed and now it is not so easy to login. But I have test script working. I hope to implement it soon.

`IMDBurlLogin = "https://secure.imdb.com/register-imdb/login#"`
`s = requests.Session()`
`webResponse = s.get(IMDBurlLogin)`

`pattern = re.compile('<a href="(https:\/\/www.imdb.com\/ap\/signin\?[\w\W]+?)"')`
`html = webResponse.text`
`ulr_imdb_login = pattern.search(html).group(1)`

`driver = webdriver.Chrome()`
`driver.get(ulr_imdb_login);`
`time.sleep(5) `
`search_box = driver.find_element_by_name('email')`
`search_box.send_keys('email@email.com')`
`search_box = driver.find_element_by_name('password')`
`search_box.send_keys('your_password')`

`search_box.submit()`
`time.sleep(5)`

`cookies = driver.get_cookies()`
`s = requests.Session()`
`for cookie in cookies:`
`    s.cookies.set(cookie['name'], cookie['value'])`
`driver.quit()`

`webResponse = s.get("http://www.imdb.com/")`

**Comment by gism** [comment]
+ Now you can introduce UserID instead of user/password

+ Regarding getMovieInfoById() error message was due to connection limitation from FA.
As filmaffinity is showing a captcha --> solution is to show captcha in order to solve it.
