### ISSUE TITLE
Why to login on FA?

### ISSUE THREAD

**Issue by rolgalan** [gism/filmaffinity2IMDB#14]
Hi,

I think login at FA is not required for exporting the movies.

Instead of request user/pass, and implement a login, it would be easier to request the user id (you can get it easily by clicking on your user name, at top right).

Then, you only need to load http://www.filmaffinity.com/en/userratings.php?user_id=XXXXX to get the movies voted by that user. This way, you can avoid all the login implementation and make the code easier.

What do you think?

**Comment by gism** [comment]
Yes, you are right. Latest code implement this option.
