### ISSUE TITLE
Error: no module named "Queue"

### ISSUE THREAD

**Issue by pablobrugarolas** [gism/filmaffinity2IMDB#15]
Hi everyone,

After running main.py, I get the following error: Import error: No module named "Queue". 

Could you help me, please?

Thank you in advance!

**Comment by txemi** [comment]
In Ubuntu I found this file in next package:

`>python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
>>> import Queue
>>> Queue.__file__
'/usr/lib/python2.7/Queue.pyc'
>>>
 >>> exit()

⟫ dpkg -S /usr/lib/python2.7/Queue.py
libpython2.7-stdlib:amd64: /usr/lib/python2.7/Queue.py `

So you should ensure this package is installed:

`sudo apt-get install libpython2.7-stdlib`

**Comment by gism** [comment]
Hi,

Normally if you have pip installed:
pip install queuelib

It works on linux, and win.

**Comment by pablobrugarolas** [comment]
Thank you, I get another error now. Should I open another issue right?
