### ISSUE TITLE
Error: No module named tabulate

### ISSUE THREAD

**Issue by pablobrugarolas** [gism/filmaffinity2IMDB#16]
Hi there, 

I get the following error: 

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate

I'm running python 2.7.12 and  I have already install tabulate by pip3 install tabulate.

Thanks

**Comment by rolgalan** [comment]
Hi burgarolaspablo,

In order to use this, you need 2 modules installed:

> pip install BeautifulSoup4
> pip install tabualate

The second line will solve your problem.

Regards

**Comment by gism** [comment]
Hi,
thanks rogalan, you are right.
these are external libraries used on the code.
we should include them in the readme, or do a setup...

please burgarolaspablo if you get more error post  them here :D

**Comment by txemi** [comment]
In last version of ubuntu you do not need to install them with pip, you can use apt.

`:~$ python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 import tabulate
 tabulate.__file__
'/usr/lib/python2.7/dist-packages/tabulate.pyc'
 
:$ dpkg -S /usr/lib/python2.7/dist-packages/tabulate.py
python-tabulate: /usr/lib/python2.7/dist-packages/tabulate.py
:$`

so you can install them with "apt-get install python-tabulate"

**Comment by pablobrugarolas** [comment]
Hi, 

It finally run main.py and got to the main menu. But I get an error when I introduce my ID. 

Do you know your FilmAffinity User ID? <Y> or <N>:y
Introduce user ID: myid
Traceback (most recent call last):
  File "main.py", line 371, in <module>
    main()
  File "main.py", line 274, in main
    fa.setUser(sUser, sPassword)
UnboundLocalError: local variable 'sUser' referenced before assignment


Thanks to all of you

**Comment by gism** [comment]
😧 no idea.
Did you change config.py.example? (There is no need, just to know)

What user ID did you introduce? User ID is not your user name, or login name. 
It is a number that is shown in the URL, for example when you check your ratings. I mean the XXX:
http://www.filmaffinity.com/es/userratings.php?user_id=XXXXXXXX

**Comment by pablobrugarolas** [comment]
Hi, 

I have changed now the config.py.example adding the id like you said (I thought it was the login name). 

Now I get the following 

change regular expression at getNumVotes() for numPages

Thank you so much

**Comment by gism** [comment]
mhhh

I don't think you introduce a correct user ID.
Do you get same error if you introduce user + password?

Just to confirm: config.py.example --> should be renamed to config.py (as explained in readme)
