### ISSUE TITLE
iMDB?

### ISSUE THREAD

**Issue by Dimas-sc** [gism/filmaffinity2IMDB#18]
Perdona que t'escrigui per aquí @gism , veig que has tret tot el tema d'importar a iMDB. Ja no és possible? Has trobat alguna alternativa per importar-hi llistes massivament? Gràcies crack

**Comment by gism** [comment]
Hola,
La verdad es que solo estaba usando el script para hacer backup  local de FA. 
He dejado de usar IMDB para consultas rápidas (no me gusta el diseño de la web). 
He quitado todo lo que había de IMDB del script....

He visto que ha cambiado un poco la interfaz de IMDB así que no es suficiente con actualizar de python 2.7 a 3.X

Estoy centrado en otro proyecto pero cuando tenga un tiempo lo reviso a ver que tal
Saludos

**Comment by gism** [comment]
@Dimas-sc, mira que te parece test_vote_imdb.py
Es muy mejorable :D pero funciona...
Solo he testeado con pocas películas, seguramente saltara el captcha de imdb y se tendrá que ver como hacer
