### ISSUE TITLE
ERROR FOUND: Connection failed at imdb.getMovieCodeByAPI()

### ISSUE THREAD

**Issue by Dimas-sc** [gism/filmaffinity2IMDB#6]
Podries fer que fos possible processar les pel·lícules per lots? Sembla que IMDB s'enfada si es fan més de X sol·licituds en menys de Y minuts.

En el meu cas tinc més de 1200 pel·lícules votades a FilmAffinity i l'script, quan recull la informació de IMDB, comença a fallar quan està més o menys al 49% (o sigui quan porta cap a 600 pel·lícules).

Potser processant de 500 en 500?

**Comment by gism** [comment]
Ara et surt un pop-up per resoldre el captcha i pots seguir tants cops com vulguis
